from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Event:
    """
    Represents a security event generated by VisionGuard AI.
    """

    event_type: str
    timestamp: datetime

    # Session information
    session_id: int

    # Recognition information
    person_name: str
    confidence: float

    # Evidence
    image_path: Optional[str] = None