from datetime import datetime

from alerts.telegram_alert import TelegramAlert
from events.event import Event
from events.event_logger import EventLogger
from events.session_manager import SessionManager
from events.session_state import SessionState
from hardware.esp8266_controller import ESP8266Controller
from utils.image_saver import ImageSaver


class EventManager:
    """
    Handles all security events generated by VisionGuard AI.
    """

    def __init__(self):

        self.logger = EventLogger()
        self.image_saver = ImageSaver()
        self.session_manager = SessionManager()

        self.telegram = TelegramAlert()
        self.esp8266 = ESP8266Controller()

    def handle(self, unknown_present, results, frame):
        """
        Process one recognition cycle.
        """

        state = self.session_manager.update(unknown_present)

        # --------------------------------------------------
        # Session Started
        # --------------------------------------------------
        if state == SessionState.STARTED:

            unknown_result = next(
                (result for result in results if not result.is_known),
                None,
            )

            if unknown_result is None:
                return

            image_path = self.image_saver.save_unknown(frame)

            event = Event(
                event_type="UNKNOWN_PERSON",
                timestamp=datetime.now(),
                session_id=self.session_manager.current_session.session_id,
                person_name="Unknown",
                confidence=unknown_result.score,
                image_path=image_path,
            )

            self.logger.log(event)

            try:
                self.telegram.send_unknown_person_alert(event)
            except Exception as e:
                print(f"[EventManager] Telegram Error: {e}")

            self.esp8266.led_on()

        # --------------------------------------------------
        # Session Active
        # --------------------------------------------------
        elif state == SessionState.ACTIVE:
            return

        # --------------------------------------------------
        # Session Ended
        # --------------------------------------------------
        elif state == SessionState.ENDED:

            self.logger.log_session_end(
                self.session_manager.last_completed_session
            )

            self.esp8266.led_off()

        # --------------------------------------------------
        # No Active Session
        # --------------------------------------------------
        else:
            return